### ISSUE TITLE
404 for precompiled assets

### ISSUE THREAD

**Issue by avdept** [joekrump/rails-turbo-vue#55]
Hey, I've used this app as template for my own app. So far everything was great and smooth, but once I tried to deploy to prod server I'm getting 404 on any assets. The assets:precompile works great, and assets put into `public/vite/assets` folder. However when opening app via browser, any assets on such url `https://domain.com/vite/assets/application-d671fe8c.css` just returns 404. Any ideas where should I look at or what did I miss? I use Capistrano for deployment

**Comment by avdept** [comment]
Ok, pls ignore this issue. I had misconfiguration in my NGINX config which led me to having 404 on any assets

**Comment by joekrump** [comment]
Glad to hear you figured it out @avdept and are finding this template to be helpful!
